// Generated by Wrangler by running `wrangler types`

interface Env {
    NODE_ENV: string
    OAUTH_KV: KVNamespace
    SSOJET_DOMAIN: string
    SSOJET_AUDIENCE: string
    SSOJET_SCOPE: string
    SSOJET_CLIENT_ID: string
    SSOJET_CLIENT_SECRET: string
    SSOJET_ISSUER: string
    API_BASE_URL: string
    MCP_OBJECT: DurableObjectNamespace<import('./src/index').AuthenticatedMCP>
    AI: Ai
}

declare namespace Cloudflare {
    interface Env {
        NODE_ENV: string
        OAUTH_KV: KVNamespace
        SSOJET_DOMAIN: string
        SSOJET_AUDIENCE: string
        SSOJET_SCOPE: string
        SSOJET_CLIENT_ID: string
        SSOJET_CLIENT_SECRET: string
        SSOJET_ISSUER: string
        API_BASE_URL: string
        MCP_OBJECT: DurableObjectNamespace<import('./src/index').AuthenticatedMCP>
        AI: Ai
    }
}
